version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: metroflow-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: metroflow-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped