"""create frequency adjustments

Revision ID: 144889cdb085
Revises: a68f323f3c4e
Create Date: 2026-08-15 03:49:05.157135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144889cdb085'
down_revision: Union[str, None] = 'a68f323f3c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('occupancy', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupancy_percentage', sa.Float(), nullable=False),
    sa.Column('current_frequency', sa.Integer(), nullable=False),
    sa.Column('recommended_frequency', sa.Integer(), nullable=False),
    sa.Column('frequency_action', sa.String(length=20), nullable=False),
    sa.Column('action_code', sa.Integer(), nullable=False),
    sa.Column('additional_trains_required', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('estimated_wait_time_impact', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frequency_adjustments_station_id'), 'frequency_adjustments', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_frequency_adjustments_station_id'), table_name='frequency_adjustments')
    op.drop_table('frequency_adjustments')
    # ### end Alembic commands ###
