"""add route id to delays

Revision ID: 31d23b54bb53
Revises: 46672278b8f7
Create Date: 2026-08-13 00:29:16.900301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d23b54bb53'
down_revision: Union[str, None] = '46672278b8f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delays', sa.Column('route_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_delays_route_id'), 'delays', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delays_route_id'), table_name='delays')
    op.drop_column('delays', 'route_id')
    # ### end Alembic commands ###
