"""initial schema

Revision ID: d9f435a9754d
Revises: 
Create Date: 2026-07-24 16:05:37.227514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f435a9754d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('distance_from_start_km', sa.Float(), nullable=True),
    sa.Column('line', sa.String(length=50), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('station_layout', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('coord_invalid', sa.Boolean(), nullable=True),
    sa.Column('distance_from_start_km_outlier', sa.Boolean(), nullable=True),
    sa.Column('opening_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_line'), 'stations', ['line'], unique=False)
    op.create_index(op.f('ix_stations_station_name'), 'stations', ['station_name'], unique=True)
    op.create_table('crowd_history',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('exit_count', sa.Integer(), nullable=True),
    sa.Column('platform_count', sa.Integer(), nullable=True),
    sa.Column('concourse_count', sa.Integer(), nullable=True),
    sa.Column('crowd_density', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_history_station_id'), 'crowd_history', ['station_id'], unique=False)
    op.create_index(op.f('ix_crowd_history_timestamp'), 'crowd_history', ['timestamp'], unique=False)
    op.create_table('crowd_predictions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('prediction_time', sa.DateTime(), nullable=False),
    sa.Column('predicted_entries', sa.Integer(), nullable=True),
    sa.Column('predicted_exits', sa.Integer(), nullable=True),
    sa.Column('predicted_platform_crowd', sa.Integer(), nullable=True),
    sa.Column('predicted_crowd_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='crowd_level'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_predictions_prediction_time'), 'crowd_predictions', ['prediction_time'], unique=False)
    op.create_index(op.f('ix_crowd_predictions_station_id'), 'crowd_predictions', ['station_id'], unique=False)
    op.create_table('passenger_journeys',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('entry_station_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('entry_gate', sa.String(length=20), nullable=True),
    sa.Column('exit_station_id', sa.Integer(), nullable=False),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('exit_gate', sa.String(length=20), nullable=True),
    sa.Column('travel_duration_mins', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['exit_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passenger_journeys_entry_station_id'), 'passenger_journeys', ['entry_station_id'], unique=False)
    op.create_index(op.f('ix_passenger_journeys_exit_station_id'), 'passenger_journeys', ['exit_station_id'], unique=False)
    op.create_table('sensor_telemetry',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('co2_ppm', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('platform_crowd', sa.Integer(), nullable=True),
    sa.Column('escalator_status', sa.Enum('WORKING', 'FAULTY', 'MAINTENANCE', 'OFFLINE', name='device_status'), nullable=True),
    sa.Column('lift_status', sa.Enum('WORKING', 'FAULTY', 'MAINTENANCE', 'OFFLINE', name='device_status'), nullable=True),
    sa.Column('camera_status', sa.Enum('WORKING', 'FAULTY', 'MAINTENANCE', 'OFFLINE', name='device_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_telemetry_station_id'), 'sensor_telemetry', ['station_id'], unique=False)
    op.create_index(op.f('ix_sensor_telemetry_timestamp'), 'sensor_telemetry', ['timestamp'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('cost_per_passenger', sa.Float(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('ticket_type', sa.Enum('SINGLE', 'RETURN', 'SMART_CARD', 'TOKEN', 'PASS', name='ticket_type'), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('fare_per_km', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('cost_exceeds_fare', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('od_pair', sa.String(length=120), nullable=True),
    sa.Column('distance_km_outlier', sa.Boolean(), nullable=True),
    sa.Column('fare_outlier', sa.Boolean(), nullable=True),
    sa.Column('cost_per_passenger_outlier', sa.Boolean(), nullable=True),
    sa.Column('passengers_outlier', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_date'), 'tickets', ['date'], unique=False)
    op.create_index(op.f('ix_tickets_from_station_id'), 'tickets', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_tickets_month'), 'tickets', ['month'], unique=False)
    op.create_index(op.f('ix_tickets_to_station_id'), 'tickets', ['to_station_id'], unique=False)
    op.create_index(op.f('ix_tickets_year'), 'tickets', ['year'], unique=False)
    op.create_table('trains',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('train_number', sa.String(length=30), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=True),
    sa.Column('line', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_station_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'DELAYED', 'OUT_OF_SERVICE', name='train_status'), nullable=True),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_current_station_id'), 'trains', ['current_station_id'], unique=False)
    op.create_index(op.f('ix_trains_line'), 'trains', ['line'], unique=False)
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('delays',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('train_id', sa.String(length=50), nullable=True),
    sa.Column('origin_station_id', sa.Integer(), nullable=False),
    sa.Column('destination_station_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('transport_type', sa.Enum('METRO', name='transport_type'), nullable=True),
    sa.Column('scheduled_departure', sa.Time(), nullable=True),
    sa.Column('scheduled_arrival', sa.Time(), nullable=True),
    sa.Column('actual_departure_delay_min', sa.Float(), nullable=True),
    sa.Column('actual_arrival_delay_min', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.Enum('SUNNY', 'CLOUDY', 'RAINY', 'STORM', 'FOG', name='weather_condition'), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_attendance_est', sa.Integer(), nullable=True),
    sa.Column('traffic_congestion_index', sa.Float(), nullable=True),
    sa.Column('holiday', sa.Boolean(), nullable=True),
    sa.Column('peak_hour', sa.Boolean(), nullable=True),
    sa.Column('weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=True),
    sa.Column('season', sa.Enum('SPRING', 'SUMMER', 'MONSOON', 'AUTUMN', 'WINTER', name='season'), nullable=True),
    sa.Column('delayed', sa.Boolean(), nullable=True),
    sa.Column('time_min', sa.Integer(), nullable=True),
    sa.Column('scheduled_departure_min', sa.Integer(), nullable=True),
    sa.Column('scheduled_arrival_min', sa.Integer(), nullable=True),
    sa.Column('is_delayed_5min', sa.Boolean(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=20), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=True),
    sa.Column('actual_departure_delay_min_outlier', sa.Boolean(), nullable=True),
    sa.Column('actual_arrival_delay_min_outlier', sa.Boolean(), nullable=True),
    sa.Column('event_attendance_est_outlier', sa.Boolean(), nullable=True),
    sa.Column('traffic_congestion_index_outlier', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delays_destination_station_id'), 'delays', ['destination_station_id'], unique=False)
    op.create_index(op.f('ix_delays_origin_station_id'), 'delays', ['origin_station_id'], unique=False)
    op.create_index(op.f('ix_delays_train_id'), 'delays', ['train_id'], unique=False)
    op.create_table('occupancy',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('train_id', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('occupancy_percentage', sa.Float(), nullable=True),
    sa.Column('crowd_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='crowd_level'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupancy_station_id'), 'occupancy', ['station_id'], unique=False)
    op.create_index(op.f('ix_occupancy_timestamp'), 'occupancy', ['timestamp'], unique=False)
    op.create_index(op.f('ix_occupancy_train_id'), 'occupancy', ['train_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('train_id', sa.String(length=50), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('stop_sequence', sa.Integer(), nullable=True),
    sa.Column('day_type', sa.Enum('WEEKDAY', 'WEEKEND', 'HOLIDAY', name='day_type'), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_station_id'), 'schedules', ['station_id'], unique=False)
    op.create_index(op.f('ix_schedules_train_id'), 'schedules', ['train_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('train_id', sa.String(length=50), nullable=False),
    sa.Column('origin_station_id', sa.Integer(), nullable=False),
    sa.Column('destination_station_id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('trip_date', sa.Date(), nullable=True),
    sa.Column('trip_duration_min', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('average_speed_kmh', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_destination_station_id'), 'trips', ['destination_station_id'], unique=False)
    op.create_index(op.f('ix_trips_origin_station_id'), 'trips', ['origin_station_id'], unique=False)
    op.create_index(op.f('ix_trips_train_id'), 'trips', ['train_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_train_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_origin_station_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_destination_station_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_schedules_train_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_station_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_occupancy_train_id'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_timestamp'), table_name='occupancy')
    op.drop_index(op.f('ix_occupancy_station_id'), table_name='occupancy')
    op.drop_table('occupancy')
    op.drop_index(op.f('ix_delays_train_id'), table_name='delays')
    op.drop_index(op.f('ix_delays_origin_station_id'), table_name='delays')
    op.drop_index(op.f('ix_delays_destination_station_id'), table_name='delays')
    op.drop_table('delays')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_line'), table_name='trains')
    op.drop_index(op.f('ix_trains_current_station_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_tickets_year'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_to_station_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_month'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_from_station_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_date'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_sensor_telemetry_timestamp'), table_name='sensor_telemetry')
    op.drop_index(op.f('ix_sensor_telemetry_station_id'), table_name='sensor_telemetry')
    op.drop_table('sensor_telemetry')
    op.drop_index(op.f('ix_passenger_journeys_exit_station_id'), table_name='passenger_journeys')
    op.drop_index(op.f('ix_passenger_journeys_entry_station_id'), table_name='passenger_journeys')
    op.drop_table('passenger_journeys')
    op.drop_index(op.f('ix_crowd_predictions_station_id'), table_name='crowd_predictions')
    op.drop_index(op.f('ix_crowd_predictions_prediction_time'), table_name='crowd_predictions')
    op.drop_table('crowd_predictions')
    op.drop_index(op.f('ix_crowd_history_timestamp'), table_name='crowd_history')
    op.drop_index(op.f('ix_crowd_history_station_id'), table_name='crowd_history')
    op.drop_table('crowd_history')
    op.drop_index(op.f('ix_stations_station_name'), table_name='stations')
    op.drop_index(op.f('ix_stations_line'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
