"use client";

import { useEffect, useState } from "react";
import { FileText, Database, Train, Brain, Clock } from "lucide-react";
import jsPDF from "jspdf";

export default function Reports() {

    const [kpi, setKpi] = useState<any>(null);
    const [forecast, setForecast] = useState<any>(null);
    const [stations, setStations] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [alerts, setAlerts] = useState<any[]>([]);
    const [aiInsight, setAiInsight] = useState("");
    const [aiLoading, setAiLoading] = useState(false);
    const downloadCSV = (
        data: any[],
        filename: string
    ) => {

        if (!data.length) return;

        const headers = Object.keys(data[0]);

        const csvRows = [
            headers.join(","),
            ...data.map(row =>
                headers.map(field =>
                    `"${row[field] ?? ""}"`
                ).join(",")
            )
        ];

        const csvContent = csvRows.join("\n");

        const blob = new Blob(
            [csvContent],
            { type: "text/csv" }
        );

        const url = window.URL.createObjectURL(blob);

        const link = document.createElement("a");

        link.href = url;
        link.download = filename;

        link.click();

        window.URL.revokeObjectURL(url);

    };

    const generateAIInsight = async () => {

        try {

            setAiLoading(true);


            const response = await fetch(
                "http://localhost:8000/api/ai/recommendation",
                {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({

                        total_passengers:
                            kpi?.total_passengers_today,

                        stations:
                            stations.length,

                        accuracy:
                            forecast?.accuracy,

                        peak_hours:
                            forecast?.peak_hours_info

                    })
                }
            );


            const data = await response.json();


            setAiInsight(
                data.recommendation ||
                data.message ||
                "No recommendation generated"
            );


        }
        catch (error) {

            console.error(
                "AI insight error",
                error
            );

            setAiInsight(
                "Unable to generate AI report"
            );

        }
        finally {

            setAiLoading(false);

        }

    };

    const generatePDF = () => {

        const doc = new jsPDF();


        doc.setFontSize(18);

        doc.text(
            "MetroFlow AI Report",
            20,
            20
        );


        doc.setFontSize(12);


        doc.text(
            `Generated Time: ${new Date().toLocaleString()}`,
            20,
            35
        );


        doc.text(
            "System Summary",
            20,
            50
        );


        doc.text(
            `Total Records: ${kpi?.forecast_records || "N/A"}`,
            20,
            65
        );


        doc.text(
            `Stations Covered: ${stations.length}`,
            20,
            75
        );


        doc.text(
            `AI Accuracy: ${forecast?.accuracy
                ?
                (forecast.accuracy * 100).toFixed(1)
                :
                "N/A"
            }%`,
            20,
            85
        );


        doc.text(
            "Forecast Information",
            20,
            105
        );


        doc.text(
            `Peak Hours: ${forecast?.peak_hours_info || "N/A"
            }`,
            20,
            120
        );


        doc.text(
            "Generated by MetroFlow AI Platform",
            20,
            150
        );


        doc.save(
            "MetroFlow_Report.pdf"
        );

    };


    useEffect(() => {

        const fetchReportData = async () => {

            try {

                const [
                    kpiResponse,
                    forecastResponse,
                    stationResponse,
                    alertResponse
                ] = await Promise.all([

                    fetch(
                        "http://localhost:8000/api/dashboard/kpi"
                    ).then(res => res.json()),


                    fetch(
                        "http://localhost:8000/api/forecast/tomorrow"
                    ).then(res => res.json()),


                    fetch(
                        "http://localhost:8000/api/crowd/all-stations"
                    ).then(res => res.json()),


                    fetch(
                        "http://localhost:8000/api/alerts/active"
                    ).then(res => res.json())

                ]);


                setKpi(kpiResponse.kpis);

                setForecast(forecastResponse);

                setStations(
                    stationResponse.stations || []
                );

                setAlerts(
                    alertResponse.alerts || []
                );

                setLoading(false);


            } catch (error) {

                console.error(
                    "Report loading error:",
                    error
                );

                setLoading(false);

            }

        };


        fetchReportData();


    }, []);



    if (loading) {

        return (

            <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center">

                Loading Reports...

            </div>

        );

    }



    return (

        <div className="min-h-screen bg-slate-950 text-white p-8">


            {/* HEADER */}

            <div className="mb-8">

                <h1 className="text-4xl font-bold">
                    📄 MetroFlow Reports
                </h1>

                <p className="text-slate-400 mt-2">
                    Operational reports and system summaries
                </p>

            </div>



            {/* SUMMARY CARDS */}

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">


                <div className="bg-slate-900 border border-slate-700 rounded-xl p-6">

                    <Database className="text-cyan-400 mb-3" />

                    <p className="text-slate-400">
                        Total Passenger Records
                    </p>

                    <h2 className="text-3xl font-bold mt-2">
                        {kpi?.forecast_records?.toLocaleString() || "N/A"}
                    </h2>

                </div>

                <div className="bg-slate-900 border border-slate-700 rounded-xl p-6">

                    <Train className="text-green-400 mb-3" />

                    <p className="text-slate-400">
                        Stations Covered
                    </p>

                    <h2 className="text-3xl font-bold mt-2">
                        {stations.length}
                    </h2>

                </div>

                <div className="bg-slate-900 border border-slate-700 rounded-xl p-6">

                    <Brain className="text-purple-400 mb-3" />

                    <p className="text-slate-400">
                        AI Model Accuracy
                    </p>


                    <h2 className="text-3xl font-bold mt-2">

                        {
                            forecast?.accuracy
                                ?
                                `${(forecast.accuracy * 100).toFixed(1)}%`
                                :
                                "N/A"
                        }

                    </h2>

                </div>

                <div className="bg-slate-900 border border-slate-700 rounded-xl p-6">

                    <Clock className="text-orange-400 mb-3" />

                    <p className="text-slate-400">
                        Generated Time
                    </p>


                    <h2 className="text-xl font-bold mt-2">

                        {new Date().toLocaleTimeString()}

                    </h2>

                </div>

            </div>

            {/* EXPORT REPORTS */}

            <div className="bg-slate-900 border border-slate-700 rounded-xl p-6 mt-8">

                <h2 className="text-xl font-bold mb-6">
                    Export Reports
                </h2>


                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">


                    <button
                        onClick={() =>
                            downloadCSV(
                                stations,
                                "station_crowd_report.csv"
                            )
                        }
                        className="bg-cyan-600 hover:bg-cyan-700 px-5 py-3 rounded-lg font-semibold"
                    >
                        🚇 Export Station Crowd CSV
                    </button>


                    <button
                        onClick={() =>
                            downloadCSV(
                                forecast?.forecast || [],
                                "passenger_forecast_report.csv"
                            )
                        }
                        className="bg-green-600 hover:bg-green-700 px-5 py-3 rounded-lg font-semibold"
                    >
                        📈 Export Forecast CSV
                    </button>


                    <button
                        onClick={() =>
                            downloadCSV(
                                alerts,
                                "alerts_report.csv"
                            )
                        }
                        className="bg-red-600 hover:bg-red-700 px-5 py-3 rounded-lg font-semibold"
                    >
                        🚨 Export Alerts CSV
                    </button>


                    <button
                        onClick={generatePDF}
                        className="bg-purple-600 hover:bg-purple-700 px-5 py-3 rounded-lg font-semibold"
                    >
                        📄 Generate PDF Report
                    </button>

                </div>

            </div>

            <div className="bg-slate-900 border border-slate-700 rounded-xl p-6 mt-8">

                <h2 className="text-xl font-bold mb-4 flex items-center gap-2">

                    🤖 AI Operational Insights

                </h2>


                <button

                    onClick={generateAIInsight}

                    className="bg-purple-600 hover:bg-purple-700 px-5 py-3 rounded-lg font-semibold"

                >

                    {
                        aiLoading
                            ?
                            "Generating..."
                            :
                            "Generate AI Insight"
                    }

                </button>



                {
                    aiInsight && (

                        <div className="mt-6 bg-slate-800 rounded-lg p-5 text-slate-300">

                            {aiInsight}

                        </div>

                    )

                }


            </div>
        </div>

    );

}