const scheduleData = [
  {
    id: 1,
    train: "DM-101",
    line: "Blue",
    from: "Noida Electronic City",
    to: "Dwarka Sector 21",
    departure: "08:30",
    arrival: "09:35",
    platform: 2,
    status: "On Time",
  },
  {
    id: 2,
    train: "DM-205",
    line: "Yellow",
    from: "Samaypur Badli",
    to: "HUDA City Centre",
    departure: "08:40",
    arrival: "09:42",
    platform: 4,
    status: "Delayed",
  },
  {
    id: 3,
    train: "DM-308",
    line: "Red",
    from: "Rithala",
    to: "Shaheed Sthal",
    departure: "08:55",
    arrival: "09:48",
    platform: 1,
    status: "Boarding",
  },
  {
    id: 4,
    train: "DM-412",
    line: "Green",
    from: "Kirti Nagar",
    to: "Brigadier Hoshiar Singh",
    departure: "09:10",
    arrival: "09:58",
    platform: 3,
    status: "On Time",
  },
  {
    id: 5,
    train: "DM-511",
    line: "Magenta",
    from: "Botanical Garden",
    to: "Janakpuri West",
    departure: "09:20",
    arrival: "10:07",
    platform: 5,
    status: "On Time",
  },
];

export default scheduleData;