import { useEffect, useState } from "react";

function History() {
  const [history, setHistory] = useState([]);
  const [search, setSearch] = useState("");

  useEffect(() => {
    try {
      const savedHistory =
        JSON.parse(
          localStorage.getItem("predictionHistory") || "[]"
        );

      setHistory(
        Array.isArray(savedHistory)
          ? savedHistory
          : []
      );
    } catch (error) {
      console.error(
        "Unable to load prediction history:",
        error
      );

      setHistory([]);
    }
  }, []);

  const filteredHistory = history.filter((item) =>
    String(item.station || "")
      .toLowerCase()
      .includes(search.toLowerCase())
  );

  const getCrowdClass = (level) => {
    const value = String(level || "").toLowerCase();

    if (value === "high") {
      return "history-high";
    }

    if (value === "medium") {
      return "history-medium";
    }

    return "history-low";
  };

  return (
    <div className="history-page">

      {/* PAGE HEADER */}
      <div className="history-header">

        <div>
          <h1>🕘 Prediction History</h1>

          <p>
            View previous AI crowd predictions
            generated by MetroFlow.
          </p>
        </div>

        <div className="history-count">
          <strong>
            {history.length}
          </strong>

          <span>
            Predictions
          </span>
        </div>

      </div>


      {/* MAIN CARD */}
      <div className="card">

        {/* CARD HEADER */}
        <div className="history-card-header">

          <div>
            <h2>
              Previous Predictions
            </h2>

            <p>
              Total records: {history.length}
            </p>
          </div>

          <input
            type="text"
            placeholder="Search by station..."
            value={search}
            onChange={(e) =>
              setSearch(e.target.value)
            }
          />

        </div>


        {/* TABLE */}
        {filteredHistory.length === 0 ? (

          <div className="history-empty">

            <div className="history-empty-icon">
              📊
            </div>

            <h3>
              No predictions yet
            </h3>

            <p>
              Run an AI crowd prediction from
              the Delhi Metro page and it will
              appear here.
            </p>

          </div>

        ) : (

          <div className="history-table-wrapper">

            <table className="history-table">

              <thead>

                <tr>

                  <th>
                    ID
                  </th>

                  <th>
                    Station
                  </th>

                  <th>
                    Date
                  </th>

                  <th>
                    Time
                  </th>

                  <th>
                    Passengers
                  </th>

                  <th>
                    Crowd Level
                  </th>

                  <th>
                    Occupancy
                  </th>

                  <th>
                    Recommendation
                  </th>

                </tr>

              </thead>


              <tbody>

                {filteredHistory.map(
                  (item, index) => (

                    <tr
                      key={
                        item.id ||
                        `${item.station}-${item.date}-${item.time}-${index}`
                      }
                    >

                      <td>
                        #{history.length - index}
                      </td>

                      <td>
                        <strong>
                          {item.station}
                        </strong>
                      </td>

                      <td>
                        {item.date}
                      </td>

                      <td>
                        {item.time}
                      </td>

                      <td>
                        {item.passenger_count}
                      </td>

                      <td>

                        <span
                          className={`history-status ${getCrowdClass(
                            item.crowd_level
                          )}`}
                        >
                          {item.crowd_level}
                        </span>

                      </td>

                      <td>
                        {item.occupancy_percent}%
                      </td>

                      <td>
                        {item.ai_recommendation}
                      </td>

                    </tr>

                  )
                )}

              </tbody>

            </table>

          </div>

        )}

      </div>

    </div>
  );
}

export default History;