version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: metroflow_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: metroflow_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=metroflow_db
      - JWT_SECRET=metroflow_super_secret_jwt_key_2026_x98f
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: metroflow_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongo_data:
